### ISSUE TITLE
Inquiry Regarding Template Choice in Contrast to CHATML

### ISSUE THREAD

**Issue by ericzhou571** [Azure99/BlossomLM#3]
Dear Azure99,

I hope this message finds you well. I am reaching out to gain a better understanding of the design choices behind the template used in your project, as opposed to the CHATML template employed by many other variants of Qwen1.5, including Liberated Qwen1.5-14b.

I've noticed that, unlike most Qwen1.5 variants that continue to utilize the CHATML template, your project adopts a distinct approach with the following structure:

```markdown
A conversation between a human user and an AI bot, where the bot responds with informative, comprehensive, and courteous replies to the inquiries posed by the human.
|Human|: Hello
|Bot|: Hello, how may I assist you today?
|Human|: Could you introduce the capital of China, please?
|Bot|: 
```

This deviation intrigues me, and I am curious about the rationale behind this choice. Is there a specific reason for avoiding the CHATML template? Could it potentially impact the performance of LLMs in some way, or is the decision aimed at circumventing certain "super strange alignments" mentioned in discussions about the Qwen1.5 series, which might degrade performance as highlighted in this thread: https://huggingface.co/Qwen/Qwen1.5-14B-Chat/discussions/2?

I am genuinely interested in understanding the thought process and considerations that guided this decision. Any insights you could share would be greatly appreciated, as it would not only satisfy my curiosity but also enhance my understanding of best practices in LLM template design.

Thank you very much for your time and for the contributions your work has made to the field. I look forward to your response.

Best regards,

**Comment by Azure99** [comment]
In fact, there aren't many particularly special designs.

The Blossom model began experiments in June last year, when the chatml template was not yet mainstream. The more common ones were alpaca and vicuna. To accommodate multi-turn dialogues, I made slight modifications to the vicuna template and have continued to use it to this day.

On the other hand, when there is an insufficient amount of data samples, explicitly specifying the dialogue continuation task (in vicuna style) in the prompt helps the model adapt to the dialogue continuation task more quickly.

**Comment by ericzhou571** [comment]
thanks a lot, I will close this issue!
