### ISSUE TITLE
有无兴趣交流一下 😊

### ISSUE THREAD

**Issue by wbopan** [Azure99/BlossomLM#5]
您好，请问这是您自己的项目吗？前段时间我在 huggingface 上注意到了您的模型，给您发了邮件，可惜没有回复。实际上我近几个月也在做类似的模型精调，这是我的主页 https://huggingface.co/wenbopan 您的数据质量很高，我在我的模型中也使用了。

不知道您有没有兴趣我们交流一下？也许可能可以合作做一些更有意思和影响力的项目？我的邮箱是 pan@wenbo.io

**Comment by Azure99** [comment]
抱歉之前没有留意邮箱，已经回复了您的邮件
