### ISSUE TITLE
模型部署问题

### ISSUE THREAD

**Issue by ailovecode** [Azure99/BlossomLM#6]
我通过transformers 进行的安装，在执行python web_demo.py后出现了
![image](https://github.com/Azure99/BlossomLM/assets/135019055/60ac1a3d-3083-4314-90cb-b4893cdf0183)
请问能帮忙看下是哪里的问题么，好像是接口不能用，但不知到怎么改。

**Comment by Azure99** [comment]
检查下accelerate和bitsandbytes是否正确安装。另外如果是本地部署的话，更建议使用ollama

**Comment by ailovecode** [comment]
> 检查下accelerate和bitsandbytes是否正确安装。另外如果是本地部署的话，更建议使用ollama

这两个依赖我都安装了，ollama我也试了但总显示远程连接被断开。

**Comment by Azure99** [comment]
ollama的提示是在pull模型时出现的吗？

**Comment by ailovecode** [comment]
> ollama的提示是在pull模型时出现的吗？

对的

**Comment by Azure99** [comment]
可以检查下代理

**Comment by ailovecode** [comment]
> 可以检查下代理

那个ollama不需要VPN吧，那我先检查一下代理。

**Comment by ailovecode** [comment]
> 我通过transformers 进行的安装，在执行python web_demo.py后出现了 ![image](https://private-user-images.githubusercontent.com/135019055/325839438-60ac1a3d-3083-4314-90cb-b4893cdf0183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDc3MDcsIm5iZiI6MTcxNDEwNzQwNywicGF0aCI6Ii8xMzUwMTkwNTUvMzI1ODM5NDM4LTYwYWMxYTNkLTMwODMtNDMxNC05MGNiLWI0ODkzY2RmMDE4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwNDU2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjVlN2YwNjY3OGM0ZWI1YmFjOGM1NmExNzVmODRjYWE2ZDU1ODVlNjNiYTNlNWExMzU0YzgxZDUyODNkYzQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yFT67FgGEfD8s0jf-4dWGSAB7_xGO3AKyjyCMFQ_W7Y) 请问能帮忙看下是哪里的问题么，好像是接口不能用，但不知到怎么改。

代理检查了也没啥问题，这个问题能解决嘛

**Comment by Azure99** [comment]
方便pip list打印一下已安装的包吗

**Comment by ailovecode** [comment]
> 方便pip list打印一下已安装的包吗

![image](https://github.com/Azure99/BlossomLM/assets/135019055/b3d6bf98-ada5-4f81-a9d6-12174716feb2)
还需要什么信息提供的么？

**Comment by Azure99** [comment]
执行accelerate test检查一下accelerate是否正确配置。
另外torch安装时需要根据官方文档，不能是cpu版本：https://pytorch.org/get-started/locally/

**Comment by ailovecode** [comment]
> 执行加速测试检查一下加速是否配置正确。 另外torch安装时需要根据官方文档，不能是cpu版本：https://pytorch.org/get-started/locally/

![image](https://github.com/Azure99/BlossomLM/assets/135019055/ff52521d-550e-4a64-9ea3-6f1f6d4d6fb1)

accelerate test 这个似乎没有问题

torch安装的时候我选择的
![image](https://github.com/Azure99/BlossomLM/assets/135019055/704b1fc5-1422-4004-8c78-e904c7836e22)
这里没有 CUDA：None   是否还要下载  CUDA ？

**Comment by Azure99** [comment]
Windows上只支持N卡，并且要安装cuda，torch这里安装时也选择对应版本。

cpu推理请使用ollama

**Comment by ailovecode** [comment]
ollama 连不上呀

**Comment by Azure99** [comment]
理解你的困惑，但是transformers确实没办法支撑cpu推理，只能考虑解决下网络问题使用ollama了

**Comment by ailovecode** [comment]
> 理解你的困惑，但是变形金刚确实无法支撑CPU推理，只能考虑使用ollama解决下网络问题了

 感谢回复！ 我安装了一个CUDA，之后运行python web_demo.py命令没有返回值了，这是什么情况
![image](https://github.com/Azure99/BlossomLM/assets/135019055/cd04f2df-4c16-47b4-ba77-16ee8d23992d)

另外问一个问题：如果通过API使用您的网页该怎么接到我自己的平台当中呢？

**Comment by Azure99** [comment]
网页demo没有提供api。
不过你可以用huggingface上的14b/9b模型的demo，这个是可以通过gradio sdk调用的。
https://huggingface.co/spaces/Azure99/Blossom-14B-Demo
https://huggingface.co/spaces/Azure99/Blossom-9B-Demo

点击最下方的**通过 API 使用**

**Comment by ailovecode** [comment]
> 网页demo没有提供api。 不过你可以用huggingface上的14b/9b模型的demo，这个是可以通过gradio sdk调用的。 https://huggingface.co/spaces/Azure99/Blossom-14B-Demo https://huggingface.co/spaces/Azure99/Blossom-9B-Demo
> 
> 点击最下方的**通过 API 使用**

感谢回复！ 我就是看到了这个API 的使用才想这个咨询一下您，那我能通过这个API使用来构建一个demo么。
跟您说下我的目的：我想构建一个基于您的模型的网页，然后我在平台上可以进行跳转并使用。

**Comment by Azure99** [comment]
huggingface上的14b和9b demo可以，这个是使用的hf的共享资源，按照ip限制请求

**Comment by ailovecode** [comment]
![image](https://github.com/Azure99/BlossomLM/assets/135019055/c16680a3-b8e8-46b4-adf0-38a1b7f04ae6)
感谢回复！！ 通过Transformers安装部署的本地上可运行了，但是没法创建共享链接。
还有您提到的按照IP限制请求，是访问您在hf中的space中的app么

**Comment by Azure99** [comment]
同样是网络问题导致的，这个是外部共享链接。你可以访问本地的127.0.0.1使用

space里的demo是按照ip限制请求频率

**Comment by ailovecode** [comment]
感谢回复！   我的天，又是网络问题；通过API的使用是不是都会存在请求限制问题。

**Comment by ailovecode** [comment]
我通过使用API实现了一个demo，这个会有什么弊端吗，比如长时间不用会自动关闭吗，或者是访问有什么限制，我用的感受是答复的比较慢。

**Comment by Azure99** [comment]
不会自动关闭，但是hf的zero gpu每次对话会先将权重移动到gpu上，会有10秒左右的开销，这就是为什么慢。另外，对于单个ip，可用计算时长是300秒，并且会根据时间恢复。

**Comment by ailovecode** [comment]
您好，我还想再咨询您一下，我现在使用的是您在hf部署的https://huggingface.co/spaces/Azure99/Blossom-14B-Demo 这个demo页面中的API，这个API的调用可以用于多人同时进行访问使用吗？

**Comment by ailovecode** [comment]
怎么会出现调用API的询问和在demo页面中的询问会有不同的答案呢（同样的问题），感觉它俩的数据集都不一样

**Comment by Azure99** [comment]
@ailovecode 

1. 理论上hf的demo和api调用应该是一样的
2. 根据调用方的ip进行限流，可以多人同时访问，但是如果同ip请求过多会被限流
3. 建议用9b的demo，最近训练了新版本，效果优于v5 14b

**Comment by ailovecode** [comment]
好的，感谢回复

**Comment by ailovecode** [comment]
@Azure99    您好，我想再问一下对于API的使用可以不通过VPN的方式来调用吗？最近要使用场景没有VPN，就调用不了的。
